"""
xml_exporter.py — FCP7 XMEML 출력 모듈
=========================================
LabeledSegment 리스트를 Premiere Pro에서 임포트 가능한
FCP7 XMEML 형식의 XML 파일로 변환한다.

핵심 결정사항 (설계도 Section 8):
    - 클립 라벨(label2) 방식 사용 안 함 → Premiere에서 불완전 지원
    - 시퀀스 마커(Sequence Marker) + 코멘트 텍스트 방식 사용
    - 마커명에 "[Green] 하이라이트" 형식으로 색깔 정보 포함
    - fps는 ffprobe 자동 감지값 사용 (수동 입력 금지)

타임코드 변환:
    초(float) → 프레임 수(int) = round(seconds × fps)
    Premiere는 프레임 단위로 마커 위치를 계산한다.

사용 예:
    from output.xml_exporter import export_xml
    path = export_xml(labeled_segments, video_info, output_dir)
    print(f"저장 완료: {path}")
"""

import xml.etree.ElementTree as ET
from datetime import datetime
from pathlib import Path
from typing import Optional

from config import OUTPUT_DIR
from core.video_inspector import VideoInfo
from scoring.labeler import LabeledSegment


# ─────────────────────────────────────────────
# Premiere 색깔 라벨 번호
# (마커 코멘트로 색깔을 전달하므로 실제로는 참고용)
# ─────────────────────────────────────────────

_LABEL_COLORS = {
    "Green":  "Green",
    "Yellow": "Yellow",
    "Blue":   "Blue",
    "Orange": "Orange",
    "Red":    "Red",
}


# ─────────────────────────────────────────────
# 공개 API
# ─────────────────────────────────────────────

def export_xml(
    labeled: list[LabeledSegment],
    video_info: VideoInfo,
    output_dir: Optional[Path] = None,
    filename: Optional[str] = None,
) -> Path:
    """
    XMEML XML 파일을 생성하고 저장 경로를 반환한다.

    Args:
        labeled     : label_segments() 반환값
        video_info  : inspect_video() 반환값 (fps, 경로 등)
        output_dir  : 출력 디렉터리. None이면 config.OUTPUT_DIR
        filename    : 파일명. None이면 자동 생성

    Returns:
        저장된 XML 파일의 Path
    """
    out_dir = output_dir or OUTPUT_DIR
    out_dir.mkdir(parents=True, exist_ok=True)

    if filename is None:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{video_info.path.stem}_markers_{ts}.xml"

    out_path = out_dir / filename

    tree = _build_xml_tree(labeled, video_info)

    # 들여쓰기 (Python 3.9+)
    ET.indent(tree, space="  ")

    tree.write(
        str(out_path),
        encoding="UTF-8",
        xml_declaration=True,
    )

    print(f"  ✅ XML 저장 완료: {out_path}")
    print(f"     마커 수: {len(labeled)}개  /  fps: {video_info.fps_int}")
    return out_path


# ─────────────────────────────────────────────
# XML 트리 구성
# ─────────────────────────────────────────────

def _build_xml_tree(
    labeled: list[LabeledSegment],
    video_info: VideoInfo,
) -> ET.ElementTree:
    """XMEML 트리를 생성한다."""

    fps = video_info.fps_int
    total_frames = seconds_to_frames(video_info.duration_sec, fps)
    video_path_url = video_info.path.resolve().as_uri()  # file:///절대경로

    # ── 루트 ──────────────────────────────────
    xmeml = ET.Element("xmeml", version="4")

    # ── sequence ──────────────────────────────
    sequence = ET.SubElement(xmeml, "sequence")
    _text(sequence, "name",
          f"{video_info.path.stem} — 편집점 분석")
    _text(sequence, "timebase", str(fps))
    _text(sequence, "ntsc", "FALSE")

    # ── media/video/track/clipitem ─────────────
    media = ET.SubElement(sequence, "media")
    video = ET.SubElement(media, "video")
    track = ET.SubElement(video, "track")
    clipitem = ET.SubElement(track, "clipitem", id="main_clip")

    _text(clipitem, "name", video_info.path.name)
    _text(clipitem, "start", "0")
    _text(clipitem, "end", str(total_frames))
    _text(clipitem, "in", "0")
    _text(clipitem, "out", str(total_frames))

    # file 참조
    file_el = ET.SubElement(clipitem, "file", id="source_file")
    _text(file_el, "name", video_info.path.name)
    _text(file_el, "pathurl", video_path_url)

    # ── 마커 삽입 ─────────────────────────────
    for seg in labeled:
        _append_marker(clipitem, seg, fps)

    # ── 생성 메타 (주석) ──────────────────────
    xmeml.insert(0, ET.Comment(
        f" Generated by 게임 실황 편집점 분석기 "
        f"| {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} "
        f"| fps={fps} "
    ))

    return ET.ElementTree(xmeml)


def _append_marker(
    clipitem: ET.Element,
    seg: LabeledSegment,
    fps: int,
) -> None:
    """clipitem에 마커 엘리먼트를 추가한다."""
    marker = ET.SubElement(clipitem, "marker")
    _text(marker, "name", seg.marker_name)
    _text(marker, "comment", seg.marker_comment)
    _text(marker, "in", str(seconds_to_frames(seg.start, fps)))
    _text(marker, "out", str(seconds_to_frames(seg.end, fps)))


# ─────────────────────────────────────────────
# 타임코드 변환
# ─────────────────────────────────────────────

def seconds_to_frames(seconds: float, fps: int) -> int:
    """
    초(float) → 프레임 수(int).

    Args:
        seconds : 타임코드 (초)
        fps     : 영상 프레임레이트 (정수)

    Returns:
        프레임 수

    Examples:
        >>> seconds_to_frames(10.5, 60)
        630
        >>> seconds_to_frames(0.0, 30)
        0
    """
    return round(seconds * fps)


def frames_to_seconds(frames: int, fps: int) -> float:
    """
    프레임 수 → 초(float).

    Examples:
        >>> frames_to_seconds(630, 60)
        10.5
    """
    return frames / fps if fps > 0 else 0.0


# ─────────────────────────────────────────────
# 헬퍼
# ─────────────────────────────────────────────

def _text(parent: ET.Element, tag: str, text: str) -> ET.Element:
    """텍스트 내용을 가진 자식 엘리먼트를 추가한다."""
    el = ET.SubElement(parent, tag)
    el.text = text
    return el


# ─────────────────────────────────────────────
# 단독 실행 테스트
# ─────────────────────────────────────────────

if __name__ == "__main__":
    import sys
    import numpy as np
    from pathlib import Path

    from core.video_inspector import VideoInfo
    from pipeline.energy_detector import EnergyResult, PeakSegment, SilenceSegment, PitchSpike
    from pipeline.whisper_transcriber import TranscriptResult, TranscriptSegment
    from scoring.exclamation_detector import detect_exclamations
    from scoring.scorer import score_segments
    from scoring.labeler import label_segments, summarize_labels

    # 더미 VideoInfo
    dummy_path = Path("game_vod_2024.mp4")
    video_info = VideoInfo(
        path=dummy_path,
        duration_sec=8073.0,   # 2시간 14분 33초
        fps=60.0,
        codec="h264",
        resolution=(1920, 1080),
        has_audio=True,
        file_size_mb=4200.0,
    )

    # 더미 에너지
    frame_times = np.linspace(0, 120, 2000)
    rms = np.random.uniform(0.1, 0.35, 2000)
    rms[400:600]  = np.random.uniform(0.80, 0.96, 200)   # 24~36s 피크
    rms[900:1100] = np.random.uniform(0.60, 0.78, 200)   # 54~66s 중간
    rms[1600:]    = np.random.uniform(0.01, 0.02, 400)   # 96~120s 침묵

    energy = EnergyResult(
        frame_times=frame_times,
        rms_curve=rms,
        peak_segments=[
            PeakSegment(start=24.0, end=36.0, peak_energy=0.94),
            PeakSegment(start=54.0, end=66.0, peak_energy=0.72),
        ],
        silence_segments=[SilenceSegment(start=96.0, end=120.0)],
        pitch_spikes=[PitchSpike(time=25.0, pitch_hz=380.0)],
        audio_path=None,
    )

    transcript = TranscriptResult(
        segments=[
            TranscriptSegment(start=24.0, end=27.0, text="야!!! 대박이다 보스 잡았어!!!"),
            TranscriptSegment(start=27.0, end=30.0, text="이겼어 클리어!!"),
            TranscriptSegment(start=54.0, end=57.0, text="ㅋㅋㅋㅋㅋ 헐 미쳤다 진짜"),
            TranscriptSegment(start=80.0, end=82.0, text="잠깐만요 화장실 다녀올게요"),
        ],
        language="ko",
        total_duration=120.0,
    )

    exclamation = detect_exclamations(transcript)
    scored = score_segments(energy, exclamation, transcript,
                            active_modules={"emotion_analyzer": True})
    labeled = label_segments(scored, user_context="다크소울 3")

    print(summarize_labels(labeled))

    out_path = export_xml(labeled, video_info)

    print(f"\n📄 생성된 XML 미리보기 (앞 50줄)")
    print("─" * 60)
    lines = out_path.read_text(encoding="utf-8").splitlines()
    for line in lines[:50]:
        print(line)
    if len(lines) > 50:
        print(f"  ... (총 {len(lines)}줄)")
